name: iaslo
contracts_folder: contracts

dependencies:
  - name: Uniswap
    github: Uniswap/v4-core
    ref: main
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.4.2

solidity:
  import_remapping:
    - "@openzeppelin=OpenZeppelin/4.4.2"

ganache:
  server:
    port: 8545

default_ecosystem: ethereum
